# Generated by Django 3.0.6 on 2020-05-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200509_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='publisher',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
